name: Deploy example site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            package
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: "./package/package-lock.json"
      - name: Install deps for package
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Pack package
        run: npm pack
      - id: upload-package
        uses: actions/upload-artifact@v7
        with:
          path: "package/*.tgz"
          archive: false
    outputs:
      package: ${{ steps.upload-package.outputs.artifact-id }}

  build-example-pages:
    needs: build-package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            example
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: "./example/package-lock.json"
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Download package artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.build-package.outputs.package }}
      - name: Install package
        run: |
          npm install ../*.tgz
          cat package.json
          ls -al node_modules
      - name: Build example site
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "example/out"

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-example-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
