name: Publish to GitHub Package Registry

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          scope: "@walk8243"
          cache: npm
          cache-dependency-path: "./package/package-lock.json"
      - id: extract_tag_version
        name: Extract tag version
        run: |
          echo "tag_version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - name: Set package version
        run: npm version --no-commit-hooks --no-git-tag-version ${{ steps.extract_tag_version.outputs.tag_version }}
      - name: Install deps for package
        run: npm ci
      - name: Build package
        run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
